# Site settings
title_left    : "shpik's "
title_right   : "world" # default: ""
description   : "Smile, Sweet, Sister, Sadistic, Surprise, Service"
keywords      : "shpik, writeup, web, pwn, rev, crypto, forensics"
url           : https://seahunoh.github.io # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : UA-XXXXX-XX
twitter_username  : "__Sehun_Oh__"
comments_enabled  : true # if enabled (set to true), please provide your disqus_username
disqus_shortname  : "shpik"
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "shpik"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog
  - slug : resume
    title: Resume

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]
